services:
  db:
    image: mysql:8.1
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - chat-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD --silent || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 20


  auth-service:
    image: projet-chat_auth-service:latest
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${AUTH_DB_NAME}
      DB_USER: ${AUTH_DB_USER}
      DB_PASSWORD: ${AUTH_DB_PASSWORD}
      DB_SYNC: "true"
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: "15m"
      INTERNAL_API_KEY: BvujKcptkLkHNXVl5ACYcNvWvNTMJ6ZABhr26mB21zzrBO99edOF5KASoVOKkj1A
      DEV_MODE: "true"
      FRONTEND_URL: "http://localhost:5000"
    ports:
      - "5002:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - chat-network

  chat-service:
    image: projet-chat_chat-service:latest
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${CHAT_DB_NAME}
      DB_USER: ${CHAT_DB_USER}
      DB_PASSWORD: ${CHAT_DB_PASSWORD}
      DB_SYNC: "true"
      JWT_SECRET: ${JWT_SECRET}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - chat-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    environment:
      # Empty string = same-origin (nginx proxies to backend)
      - API_BASE_URL=
      - BACKEND_ADDRESS=
      - WS_ENDPOINT=ws://localhost:4001
    ports:
      - "5000:80"
    depends_on:
      - chat-service
      - auth-service
    networks:
      - chat-network

  ws-local-service:
    build:
      context: ./ws-local-service
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 4001
      CHAT_SERVICE_INTERNAL: http://chat-service:5000
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
    ports:
      - "4001:4001"
    networks:
      - chat-network
    depends_on:
      - chat-service
      - auth-service


networks:
  chat-network:
    driver: bridge

volumes:
  db_data:
